apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod14
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: registry.gitlab.com/devops5764541/k8s_data/shan:v
    ports:
    - containerPort: 80
    imagePullPolicy: Always   
  imagePullSecrets:            
    - name: app-secret
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

